export enum PalanteErrorCodes {
  SESSION_NOT_FOUND = "SessionNotFound",
  CART_NOT_FOUND = "CartNotFound",
  EMPTY_CART = "EmptyCart",
  STORE_NOT_FOUND = "StoreNotFound",
  ADDRESS_NOT_FOUND = "AddressNotFound",
  LINE_ITEM_NON_POSITIVE_QUANTITY = "LineItemNonPositiveQuantity",
  ITEM_NOT_FROM_CART_STORE = "ItemNotFromCartStore",
  PRODUCT_NOT_FOUND = "ProductNotFound",
  PRODUCT_STOCK_EXCEEDED = "ProductStockExceeded",
  PRODUCT_MAX_STOCK_PER_ORDER_EXCEEDED = "ProductMaxStockPerOrderExceeded",
  USER_HAS_NO_ADDRESSES = "UserHasNoAddresses",
  LINE_ITEM_NOT_FOUND = "LineItemNotFound",
  LINE_ITEM_NOT_FROM_CART = "LineItemNotFromCart",
  CART_ADDRESS_NOT_SET = "CartAddressNotSet",
  COUPON_NOT_FOUND = "CouponNotFound",
  COUPON_STORE_NOT_FOUND = "CouponStoreNotFound",
  COUPON_NOT_VALID = "CouponNotValid",
  COUPON_EXPIRED = "CouponExpired",
  META_ITEM_NOT_FOUND = "MetaItemNotFound",
}
